export const jobs = [
  {
    id: 501,
    companyName: 'abc',
    jobTitle: 'ba-101',
    publishDate: null,
    expectedClosureDate: [2024, 1, 22],
    employeeType: 'Remote',
    salary: '1000-2000',
    status: 'On Hold',
  },
  {
    id: 500,
    companyName: 'abc',
    jobTitle: 'Title',
    publishDate: null,
    expectedClosureDate: [2024, 2, 2],
    employeeType: 'Remote',
    salary: '3000-5000',
    status: 'In Progress',
  },
  {
    id: 499,
    companyName: 'abc',
    jobTitle: 'Software Development Engineer in Test',
    publishDate: null,
    expectedClosureDate: [2024, 1, 21],
    employeeType: 'Contract',
    salary: '50,000-60,000',
    status: 'Closed',
  },
  {
    id: 498,
    companyName: 'Talrise',
    jobTitle: 'Cloud Architect',
    publishDate: null,
    expectedClosureDate: [2024, 1, 22],
    employeeType: 'Contract',
    salary: '3000-5000',
    status: 'Closed',
  },
  {
    id: 497,
    companyName: 'abc',
    jobTitle: 'aslinda',
    publishDate: null,
    expectedClosureDate: [2024, 1, 18],
    employeeType: 'Remote',
    salary: '50,000-60,000',
    status: 'In Progress',
  },
  {
    id: 496,
    companyName: 'akin Solutions',
    jobTitle: 'aslinda',
    publishDate: null,
    expectedClosureDate: [2024, 2, 1],
    employeeType: 'Remote',
    salary: '1000-2000',
    status: 'Closed',
  },
  {
    id: 495,
    companyName: 'abc',
    jobTitle: 'Senior',
    publishDate: null,
    expectedClosureDate: [2024, 3, 7],
    employeeType: 'Contract',
    salary: '1000-2000',
    status: 'Closed',
  },
  {
    id: 494,
    companyName: 'wandern Solutions',
    jobTitle: 'Backend Developer',
    publishDate: null,
    expectedClosureDate: [2024, 1, 24],
    employeeType: 'Remote',
    salary: '3000-5000',
    status: 'In Progress',
  },
  {
    id: 493,
    companyName: 'wandern Solutions',
    jobTitle: 'backend developer',
    publishDate: null,
    expectedClosureDate: [2024, 1, 18],
    employeeType: 'Full Time',
    salary: '50,000-60,000',
    status: 'Withdrawn',
  },
  {
    id: 492,
    companyName: 'abc',
    jobTitle: 'gfjh',
    publishDate: null,
    expectedClosureDate: [2024, 1, 19],
    employeeType: 'Full Time',
    salary: '1000-2000',
    status: 'On Hold',
  },
]

export const statuses = ['PROPOSAL', 'IN_PROGRESS', 'HOLD_ON', 'CLOSED', 'WITHDRAW']
